name:                 network-scanner
version:              0.1.0.0
visibility:           public
id:                   network-scanner-0.1.0.0-inplace
key:                  network-scanner-0.1.0.0-inplace
license:              BSD-3-Clause
copyright:            2025 Cleisson Barbosa
maintainer:           example@example.com
author:               Cleisson Barbosa
homepage:             https://github.com/cleissonbarbosa/network-scanner#readme
description:
    Please see the README on GitHub at <https://github.com/cleissonbarbosa/network-scanner#readme>

abi:                  inplace
exposed:              True
exposed-modules:      Lib
hidden-modules:       Paths_network_scanner
import-dirs:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/build

library-dirs:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/build

library-dirs-static:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/build

dynamic-library-dirs:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/build

data-dir:             /home/runner/work/network-scanner/network-scanner/.
hs-libraries:         HSnetwork-scanner-0.1.0.0-inplace
depends:
    async-2.2.5-0b232247b7800d4c476adf5e0b0a4c292747c836480029a4a12476a28ea5f39a
    base-4.21.0.0-ae91 bytestring-0.12.2.0-7dd0
    network-3.2.8.0-3303c0294581fb2eb95050a17af2c95f20f5193ec9b47d3a10ff6d66ebbfc066
    process-1.6.25.0-5f54 time-1.14-9bf8

haddock-interfaces:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/doc/html/network-scanner/network-scanner.haddock

haddock-html:
    /home/runner/work/network-scanner/network-scanner/dist-newstyle/build/x86_64-linux/ghc-9.12.2/network-scanner-0.1.0.0/doc/html/network-scanner
